version: '3'
services:
  plod:
    build: ./
    working_dir: /var/www/html/
    volumes:
      - ./public/.:/var/www/html/public/
    ports:
      - 8000:8000
    links:
      - plod-db
  plod-db:
    container_name: plod-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mydbdata:/var/lib/mysql
  datadog:
    image: gcr.io/datadoghq/agent:7
    links:
     - redis # ensures that redis is a host that the container can find
     - web # ensures that the web app can send metrics
    environment:
     - DD_SITE=us5.datadoghq.com
     - DD_API_KEY=
     - DD_LOGS_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  my-db: